---
title: "Final Assignment"
author:
 - name: "Noora Sheridan"
 - "noora.sheridan@aalto.fi"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
  toc: true
  code_folding: hide
  fig_caption: true
  fig_width: 8
  fig_height: 8
  theme: yeti
---

## Overview of the research

In this assignment I am analysing Helsinki Region Transport (HSL) customer satisfaction survey. This dataset has been wrangled to meet the needs of my analysis, and the wrangling script is available [here](https://github.com/v-a-l-a/IODS-final/blob/master/hsl_data.R). I will use the logistic regression method to see whether or not specific variables such as gender, availability of seats and punctuality of transport to explain the target variable overall grade given to HSL. The aim is to identify factors related to high / low satisfaction with HSL.

**Research question**: Which of the following variables are related to high satisfaction HSL: punctuality, space, meeting travel needs, gender, age, access to a car, value for money and frequency of use?

**My hypothesis**: All of the variables except for gender and age are related to satisfaction with HSL:

+ Punctuality: the more punctual the transportation, the more satisfied customers are
+ Space: the more available seats there are, the more satisfied customers are
+ Meeting travel needs: the more HSL transportation meets their needs, the more satisfied customers are
+ Access to car: customers without access to car are happier with HSL (since they don't have an alternative)
+ Value for money: customers who see HSL as bringing good value for money are happier with HSL
+ Frequency of use: the more frequent the use of HSL transportation, the more satisfied customers are (since they haven't changed to another alternative - some users may on purpose avoid HSL leading to less frequent use)

## The HSL dataset
Description of your data and its variables. 
what does it relate to, what do the variables represent, what has been done to the data before analysis?

The original dataset includes all responses to the HSL customer satisfaction survey openly available [here](https://hsl.louhin.com/asty/help). The original dataset has 340 378 observations and 127 variables, with the variables relating to questions about the respondent (e.g. age, gender, occupation), to their travel (e.g. frequency of use of current buss / train, access to a car), to their opinion about HSL transportation (e.g. customer service, tidyness of buses etc., overall grade given to HSL) and to other factors such as how they search for information about timetables or pay for their journeys.

The first task in my data wrangling was to choose the variables to analyse because of the large number of variables and observations in the original dataset. Moreover, when exploring the variables, I noticed that some of them had a lot of missing values. For example the variable 'K1A8L' (the ferry's timetables suit my travel needs) has over 331 000 missing answers, probably explained by the fact that not many people use a ferry on day-to-day travel. However, the variable 'K3B' (overall grade for HSL-region public transport) is only missing some 10 000 responses out of over 340 000.

Here are the variables chosen for this study and the statements / questions relating to them:

+ **Punctuality**: buses / carriages / ferries run according to timetable (5 levels, 1 = very badly, 5 = very well)
+ **Space**: there are seats available on this route at this time of the day (5 levels, 1 = very badly, 5 = very well)
+ **Meets_needs**: the route / metro / local train meets my travel needs (5 levels, 1 = very badly, 5 = very well)
+ **Gender**: gender (2 levels, 1 = female, 2 = male)
+ **Age**: age group (5 levels, 1 = 15-19 years, 2 = 20-29, 3 = 30-44, 4 = 45-59, 5 = 60+)
+ **Car**: would you have had access to a car for this journey (2 levels, 1 = yes, 2 = no)
+ **Worth**: public transportation gives value for money (2 levels, 1 = yes, 2 = no)
+ **Frequency**: how often on average do you travel on this route? (4 levels, 1 = at least 4 days a week, 2 = 2-3 days a week, 3 = once a week, 4 = less frequently)
+ **High_grade**: overall grade given to HSL-region transportation (2 levels, true = grade 4 or 5, false = grade 1, 2 or 3)

## The variables

so many plots

## Logistic regression
